fix the bug of d3 dependencies
the d3's dependence d3-request 1.0.6 will breaks webpack build. error is as follows
XMLHttpRequest.js:15 Uncaught Error: Cannot find module "child_process"

So locking the version of d3 to avoid higher version of d3 requires d3-request-1.0.6

Signed-off-by: Zeyu Zhu <zhuzeyu0409@gmail.com>